name: CI/CD for Google Colab

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        

      - name: Install dependencies
        run: |
          pip install -r requirements.txt 

      - name: Run Python script in Google Colab
        run: |
          pip install jupyterlab
          jupyter nbconvert --to notebook --execute test.ipynb --output executed_test.ipynb
